version: "3.9"
services:
  backend:
    build: .
    volumes:
      - .:/app
      - uploads:/app/uploads
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  bot:
    build: .
    depends_on:
      - backend
    volumes:
      - .:/app
      - uploads:/app/uploads
    env_file:
      - .env
    command: python app/bot.py

  nginx:
    image: nginx:stable
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - uploads:/uploads:ro

volumes:
  uploads:
